[debug] not up to date. inChanged = true, force = false
[debug] Updating ...
[error] lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/5.3.0/kafka-avro-serializer-5.3.0.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/5.3.0/kafka-avro-serializer-5.3.0.jar
[error] https://packages.confluent.io/maven/io/confluent/common-config/5.3.0/common-config-5.3.0.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/common-config/5.3.0/common-config-5.3.0.jar
[error] https://packages.confluent.io/maven/io/confluent/common-utils/5.3.0/common-utils-5.3.0.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/common-utils/5.3.0/common-utils-5.3.0.jar
[error] https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/5.3.0/kafka-schema-registry-client-5.3.0.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/5.3.0/kafka-schema-registry-client-5.3.0.jar
[error] https://packages.confluent.io/maven/org/apache/kafka/kafka-clients/5.3.0-ccs/kafka-clients-5.3.0-ccs.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/org/apache/kafka/kafka-clients/5.3.0-ccs/kafka-clients-5.3.0-ccs.jar
[error] 
[error] 	at lmcoursier.internal.shaded.coursier.Artifacts$.$anonfun$fetchArtifacts$9(Artifacts.scala:365)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$extension$1$adapted(Task.scala:14)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.wrap(Task.scala:82)
[error] 	at lmcoursier.internal.shaded.coursier.util.Task$.$anonfun$flatMap$2(Task.scala:14)
[error] 	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: lmcoursier.internal.shaded.coursier.cache.ArtifactError$DownloadError: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/5.3.0/kafka-avro-serializer-5.3.0.jar
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.helper$2(Downloader.scala:793)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.coursier$cache$internal$Downloader$$downloading(Downloader.scala:806)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:415)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$remote$6(Downloader.scala:533)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[error] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
[error] 	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
[error] 	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
[error] 	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
[error] 	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
[error] 	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
[error] 	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
[error] 	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
[error] 	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
[error] 	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
[error] 	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
[error] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
[error] 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[error] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:329)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.redirectTo(CacheUrl.scala:179)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.redirect(CacheUrl.scala:194)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheUrl$.urlConnectionMaybePartial(CacheUrl.scala:350)
[error] 	at lmcoursier.internal.shaded.coursier.cache.ConnectionBuilder.connectionMaybePartial(ConnectionBuilder.scala:50)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.doDownload(Downloader.scala:222)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$2(Downloader.scala:410)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.loop$1(CacheLocks.scala:73)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:93)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.$anonfun$remote$1(Downloader.scala:413)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.$anonfun$downloading$1(Downloader.scala:764)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withUrlLock(CacheLocks.scala:112)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.helper$2(Downloader.scala:764)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$.coursier$cache$internal$Downloader$$downloading(Downloader.scala:806)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:415)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$remote$6(Downloader.scala:533)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (update) lmcoursier.internal.shaded.coursier.error.FetchError$DownloadingArtifacts: Error fetching artifacts:
[error] https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/5.3.0/kafka-avro-serializer-5.3.0.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/kafka-avro-serializer/5.3.0/kafka-avro-serializer-5.3.0.jar
[error] https://packages.confluent.io/maven/io/confluent/common-config/5.3.0/common-config-5.3.0.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/common-config/5.3.0/common-config-5.3.0.jar
[error] https://packages.confluent.io/maven/io/confluent/common-utils/5.3.0/common-utils-5.3.0.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/common-utils/5.3.0/common-utils-5.3.0.jar
[error] https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/5.3.0/kafka-schema-registry-client-5.3.0.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/io/confluent/kafka-schema-registry-client/5.3.0/kafka-schema-registry-client-5.3.0.jar
[error] https://packages.confluent.io/maven/org/apache/kafka/kafka-clients/5.3.0-ccs/kafka-clients-5.3.0-ccs.jar: download error: Caught javax.net.ssl.SSLHandshakeException (Received fatal alert: handshake_failure) while downloading https://packages.confluent.io/maven/org/apache/kafka/kafka-clients/5.3.0-ccs/kafka-clients-5.3.0-ccs.jar
